services:
  finnkino-ui:
    container_name: finnkino-ui
    build:
      context: .
    restart: unless-stopped
    pull_policy: build
    hostname: finnkino-ui
    networks:
      macvlan:
    ports:
      - "80:80"

networks:
  macvlan:
    external: true
